import {TubFlight,WIDTH,HEIGHT,TARGET} from './engine.mjs';
export const FUEL_KEY='mbs-fuel-flight-v1';
export function fuelUnlocked(store=localStorage){try{const value=JSON.parse(store.getItem(FUEL_KEY));return value?.version===1&&value.pipes===8&&Number.isSafeInteger(value.completedAt)&&value.completedAt>0;}catch{return false;}}
export function mountTubFlight(host,{onComplete=()=>{},title='TUB FLIGHT',autoFuel=false}={}){
 const game=new TubFlight();let frame=0,last=0,paused=false,ended=false,disposed=false,redirect=0;
 host.classList.add('tub-flight');host.innerHTML='<div class="tub-title"><strong></strong><span>SPONSORED SOFTWARE · 1995</span></div><p class="tub-caption">Keep the tub afloat. Clear eight pipes. Catch eight scoops.</p><div class="tub-screen"><canvas width="320" height="420" tabindex="0" aria-label="Fuel tub flight game. Tap or press Space to flap."></canvas><div class="tub-message" role="status"></div></div><div class="tub-controls"><button type="button" data-flap>FLAP ↑</button><button type="button" data-retry hidden>TRY AGAIN ↻</button><button type="button" data-pause>Pause</button></div><p class="tub-note">Optional arcade break. This game never unlocks the rest of the site.</p>';
 host.querySelector('.tub-title strong').textContent=title;const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d'),message=host.querySelector('.tub-message'),flapButton=host.querySelector('[data-flap]'),retry=host.querySelector('[data-retry]'),pause=host.querySelector('[data-pause]');
 function tub(x,y,tilt=0){ctx.save();ctx.translate(x,y);ctx.rotate(tilt);ctx.fillStyle='#eee4ff';ctx.fillRect(-15,-17,30,34);ctx.fillStyle='#692ca7';ctx.fillRect(-15,-3,30,14);ctx.fillStyle='#b5ff23';ctx.fillRect(-17,-21,34,7);ctx.fillStyle='#edffb8';ctx.fillRect(-11,14-game.powder*3.8,22,game.powder*3.8);ctx.fillStyle='#291044';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText('FUEL',0,6);ctx.restore();}
 function draw(){ctx.imageSmoothingEnabled=false;ctx.fillStyle='#130e2c';ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#31254d';for(let x=0;x<WIDTH;x+=32){const y=300+(x%3)*7;ctx.fillRect(x,y,22,HEIGHT-y);ctx.fillStyle='#617348';ctx.fillRect(x+5,y+12,3,3);ctx.fillStyle='#31254d';}ctx.fillStyle='#74548f';for(let i=0;i<25;i++)ctx.fillRect((i*73)%320,(i*53)%285,2,2);
  for(const p of game.pipes){const top=p.gap-75,bottom=p.gap+75;ctx.fillStyle='#216d68';ctx.fillRect(p.x,0,44,top);ctx.fillRect(p.x,bottom,44,HEIGHT-bottom);ctx.fillStyle='#7ce8b5';ctx.fillRect(p.x+4,0,7,top);ctx.fillRect(p.x+4,bottom,7,HEIGHT-bottom);ctx.fillStyle='#ade2be';ctx.fillRect(p.x-5,top-14,54,14);ctx.fillRect(p.x-5,bottom,54,14);ctx.fillStyle='#193b48';ctx.fillRect(p.x+15,top-10,14,8);ctx.fillRect(p.x+15,bottom+3,14,8);}
  if(game.lastDose){const age=game.elapsed-game.lastDose.at;if(age<.8){for(let i=0;i<10;i++){const t=Math.min(1,(age+i*.015)/.8);ctx.fillStyle='#e9ffc9';ctx.fillRect(game.lastDose.x+(82-game.lastDose.x)*t+Math.sin(i*3)*8,game.lastDose.y+(game.y-game.lastDose.y)*t,2,3);}}}
  tub(82,game.y,Math.max(-.35,Math.min(.65,game.velocity/650)));ctx.fillStyle='#bdd861';ctx.fillRect(0,HEIGHT-18,WIDTH,18);ctx.fillStyle='#172528';for(let x=0;x<WIDTH;x+=16)ctx.fillRect(x,HEIGHT-15,9,4);
  ctx.textAlign='left';ctx.font='bold 18px monospace';ctx.fillStyle='#efffc9';ctx.fillText(`${game.score} / ${TARGET} PIPES`,14,29);ctx.font='11px monospace';ctx.fillStyle='#97caca';ctx.fillText('MOM’S AERIAL DOSING LINE',14,45);
 }
 function paint(){draw();const ready=game.phase==='ready',crashed=game.phase==='crashed',complete=game.phase==='complete';message.hidden=game.phase==='running'&&!paused;message.textContent=paused?'PAUSED':ready?'TAP TO KEEP IT UP':crashed?'TUB DOWN. SCOOPS RESET.':complete?'EIGHT PIPES. ONE FULL TUB.':'';retry.hidden=!crashed&&!complete;flapButton.hidden=crashed||complete;pause.disabled=ready||crashed||complete;pause.textContent=paused?'Resume':'Pause';canvas.setAttribute('aria-label',`Fuel tub flight. ${game.score} of eight pipes. ${game.phase}. Tap or press Space to flap.`);}
 function tick(now){frame=0;if(disposed)return;const dt=last?(now-last)/1000:0;last=now;if(!paused&&!document.hidden)game.step(dt);paint();if(game.phase==='complete'&&!ended){ended=true;const receipt={version:1,pipes:8,completedAt:Date.now()};try{localStorage.setItem(FUEL_KEY,JSON.stringify(receipt));}catch{}onComplete(receipt);if(autoFuel)redirect=setTimeout(()=>location.assign('/games/fuel/'),0);}if(game.phase==='running'&&!paused&&!document.hidden)frame=requestAnimationFrame(tick);}
 function schedule(){if(frame)cancelAnimationFrame(frame);frame=0;last=0;if(game.phase==='running'&&!paused&&!document.hidden)frame=requestAnimationFrame(tick);paint();}
 function flap(){if(paused)return;if(game.flap()){if(!frame){last=performance.now();frame=requestAnimationFrame(tick);}paint();}}
 const pointer=e=>{e.preventDefault();flap();};const key=e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();flap();}};
 canvas.addEventListener('pointerdown',pointer);canvas.addEventListener('keydown',key);flapButton.onclick=flap;retry.onclick=()=>{clearTimeout(redirect);game.reset();ended=false;paused=false;paint();canvas.focus();};pause.onclick=()=>{paused=!paused;schedule();};
 function visibility(){if(document.hidden){paused=true;}schedule();}document.addEventListener('visibilitychange',visibility);paint();
 return {game,pause(){paused=true;schedule();},dispose(){disposed=true;if(frame)cancelAnimationFrame(frame);clearTimeout(redirect);canvas.removeEventListener('pointerdown',pointer);canvas.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',visibility);host.replaceChildren();}};
}
