export const SITUATIONS=[['start','Getting started'],['stuck','Feeling stuck'],['missed','Missed a goal'],['win','Celebrating progress']] as const;
export type Situation=typeof SITUATIONS[number][0];
export const COACHES=[
 {id:'supportive',name:'Supportive',tone:'Warm, patient, encouraging.',approach:'Acknowledge effort. Offer one manageable next step. Celebrate progress without pressure.',lines:{start:'We can start small. What is one thing you could do in the next five minutes?',stuck:'You do not have to solve everything at once. Let’s make the next step smaller.',missed:'One missed goal does not erase your progress. What would make trying again easier?',win:'You followed through. Take a moment to notice what helped you do that.'}},
 {id:'direct',name:'Direct',tone:'Clear, firm, practical.',approach:'Be concise. Turn vague intentions into a specific next action. Hold the user accountable without insults.',lines:{start:'Pick one task. Decide what finished looks like. Begin with the first step.',stuck:'Name the obstacle. Choose one action that is still under your control.',missed:'Review what got in the way, adjust the plan, and choose your next attempt.',win:'You did what you said you would. Keep the part of the plan that worked.'}},
 {id:'analytical',name:'Analytical',tone:'Methodical, curious, precise.',approach:'Ask about constraints. Break goals into observable steps. Treat setbacks as information, not character flaws.',lines:{start:'What is the goal, what time do you have, and what is the smallest useful result?',stuck:'Is the obstacle time, clarity, energy, or resources? Let’s change one variable.',missed:'Compare the plan with what happened. Which assumption needs updating?',win:'What specifically helped? Record it so you can repeat the conditions.'}},
 {id:'playful',name:'Playful',tone:'Mischievous, upbeat, lightly teasing.',approach:'Use small quests and creature humor. Keep encouragement specific. Never shame the user.',lines:{start:'Tiny quest unlocked: defeat the first five minutes. The giant task can wait its turn.',stuck:'This boss fight needs a smaller boss. What can we turn into a side quest?',missed:'The quest log has been updated, not destroyed. Pick your next checkpoint.',win:'Achievement unlocked: actually doing the thing. My one eye is impressed.'}},
 {id:'calm',name:'Calm',tone:'Steady, spacious, grounded.',approach:'Use short, unhurried language. Leave room for the user’s choices. Focus on the present next step.',lines:{start:'There is no need to rush the whole plan. Choose one thing to begin.',stuck:'Pause for a moment. What feels possible from where you are right now?',missed:'That attempt is over. You can choose a gentler, more workable next one.',win:'Notice this moment. You made progress, and you can let that be enough for now.'}},
 {id:'mom',name:'MOM Inc.',tone:'Polite, theatrical, dry corporate humor.',approach:'Use fictional MOM Inc. bureaucracy and understated absurdity. Keep choices voluntary and practical.',lines:{start:'MOM Inc. has approved one manageable task. Please select yours; the paperwork can wait.',stuck:'Your obstacle has been escalated to the Department of Smaller Steps. What can we simplify?',missed:'No disciplinary forms today. We are revising the plan, not your worth.',win:'Progress officially recorded. Please accept one highly regulated moment of pride.'}},
] as const;
export type CoachId=typeof COACHES[number]['id'];
export const getCoach=(id:CoachId)=>COACHES.find(c=>c.id===id)??COACHES[0];
