'use client';
import {AnatomyPanel} from './anatomy-panel';
import {CoachingPanel} from './coaching-panel';
import {PUPILS,type PupilShape} from './pupils';
import {useEffect,useRef,useState} from 'react';
import {Dices,Download,Undo2,Redo2,Lock,Unlock,Play,Pause,RotateCcw,Rotate3D,ChevronLeft,ChevronRight,Save,Upload,Layers3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlienViewer,type ViewerHandle} from './alien-viewer';
import {fresh,parseRecipe,STYLES,REGIONS,LABELS,type Region,type Design} from './design';
type History={past:Design[];now:Design;future:Design[]};
export default function Home(){
 const [h,setH]=useState<History>({past:[],now:fresh(),future:[]});const [selected,setSelected]=useState<Region>('head');const [locks,setLocks]=useState<Region[]>([]);const [holo,setHolo]=useState(false),[parts,setParts]=useState(false),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[restored,setRestored]=useState(false),[dialog,setDialog]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const viewer=useRef<ViewerHandle>(null);const upload=useRef<HTMLInputElement>(null);const design=h.now,style=STYLES[design.styles[selected]];
 const commit=(next:Design)=>setH(old=>JSON.stringify(next)===JSON.stringify(old.now)?old:{past:[...old.past,old.now].slice(-60),now:next,future:[]});
 useEffect(()=>{try{const saved=localStorage.getItem('myr5-recipe-v1');if(saved)setH({past:[],now:parseRecipe(saved),future:[]});}catch{}setRestored(true);},[]);
 useEffect(()=>{if(restored)try{localStorage.setItem('myr5-recipe-v1',JSON.stringify(design));}catch{}},[design,restored]);
 useEffect(()=>{if(message){const timer=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(timer);}},[message]);
 const pick=(id:number)=>commit({...design,styles:{...design.styles,[selected]:(id+20)%20}});
 const apply=(id:number)=>commit({...design,styles:Object.fromEntries(REGIONS.map(r=>[r,locks.includes(r)?design.styles[r]:id])) as Design['styles']});
 const remix=()=>{if(locks.length===REGIONS.length){setMessage('Unlock a section to remix.');return;}const nums=crypto.getRandomValues(new Uint32Array(6));commit({...design,styles:Object.fromEntries(REGIONS.map((r,i)=>[r,locks.includes(r)?design.styles[r]:nums[i]%20])) as Design['styles']});};
 const save=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(design,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='myr5-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);};
 async function exportFile(format:'glb'|'obj'|'png'){setBusy(true);try{await viewer.current?.exportFile(format);setMessage('Your download is ready.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed.');}finally{setBusy(false);}}
 return <main className="creator-shell">
 <header className="topbar"><div className="brand-copy"><img className="mom-mark" src="/mom-inc-mark.png" alt="MOM Inc."/><p>MOM INC. / SPECIMEN DIVISION</p><h1>MYR5 <span className="lab-title">/ Creature studio</span></h1></div><div className="top-actions"><a className="coach-animation-link" href="/animation/index.html">Animate coach ↗</a><Button variant="ghost" size="icon" aria-label="Undo" disabled={!h.past.length} onClick={()=>setH(o=>({past:o.past.slice(0,-1),now:o.past.at(-1)!,future:[o.now,...o.future]}))}><Undo2/></Button><Button variant="ghost" size="icon" aria-label="Redo" disabled={!h.future.length} onClick={()=>setH(o=>({past:[...o.past,o.now],now:o.future[0],future:o.future.slice(1)}))}><Redo2/></Button><Button variant="outline" onClick={remix}><Dices/>Remix</Button><Button disabled={!ready} onClick={()=>setDialog(true)}><Download/>Export model</Button></div></header>
 <section className="creator-grid"><aside className="region-panel" aria-label="Creature sections"><div className="panel-kicker">ANATOMY</div><h2>Structure</h2><p className="panel-intro">Select a region to modify.</p><div className="region-list">{REGIONS.map((r,i)=><div key={r} className={'region-card '+(selected===r?'is-active':'')}><div className="region-card-heading"><button className="region-pick" aria-pressed={selected===r} onClick={()=>setSelected(r)}><span className="region-index">0{i+1}</span><span className="region-name"><strong>{LABELS[r]}</strong><small>{STYLES[design.styles[r]].name}</small></span></button><Button variant="ghost" size="icon" aria-label={(locks.includes(r)?'Unlock ':'Lock ')+LABELS[r]} aria-pressed={locks.includes(r)} onClick={()=>setLocks(x=>x.includes(r)?x.filter(v=>v!==r):[...x,r])}>{locks.includes(r)?<Lock/>:<Unlock/>}</Button></div></div>)}</div><CoachingPanel value={design.coach} onChange={coach=>commit({...design,coach})}/><div className="recipe-actions"><Button variant="outline" onClick={save}><Save/>Save</Button><Button variant="outline" onClick={()=>upload.current?.click()}><Upload/>Load</Button></div><input hidden ref={upload} type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file){try{if(file.size>20000)throw Error('Choose a MYR5 recipe file.');commit(parseRecipe(await file.text()));setMessage('Recipe restored.');}catch(err){setMessage(err instanceof Error?err.message:'Invalid recipe.');}e.target.value='';}}}/><Button className="reset-design" variant="ghost" onClick={()=>{commit(fresh());setMessage('Original MYR5 restored.');}}><RotateCcw/>Original creature</Button><p className="small-note">Locks protect parts during Remix and whole-creature changes.</p></aside>
 <section className="viewport-panel" aria-label="Interactive MYR5 model"><AlienViewer ref={viewer} design={design} selected={selected} hologram={holo} parts={parts} playing={playing&&!dialog} onPick={setSelected} onReady={()=>setReady(true)}/><div className="protective-glass"><div className="glass-edge"/><div className="glass-reflection"/></div><div className="viewport-chrome"><span className="live-badge">● {holo?'HOLOGRAM':'SPECIMEN 005'}</span></div><div className="orbit-hint">Drag to rotate · scroll to zoom · tap a part</div><div className="view-tools"><Button title="Front view" aria-label="Front view" onClick={()=>{setPlaying(false);viewer.current?.front();}}><RotateCcw/></Button><Button title="Back view" aria-label="Back view" onClick={()=>{setPlaying(false);viewer.current?.back();}}><Rotate3D/></Button><Button title={playing?'Pause rotation':'Rotate automatically'} aria-label={playing?'Pause rotation':'Rotate automatically'} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause/>:<Play/>}</Button><Button className="parts-button" aria-pressed={parts} onClick={()=>setParts(p=>!p)}><Layers3/>Parts</Button></div><div className="specimen-label"><span><small>MYR5 · LIVE SPECIMEN</small><strong>{style.name.toUpperCase()}</strong></span></div></section>
 <aside className="style-panel" aria-label="Creature styles"><div className="panel-kicker">MATERIAL / {selected==='head'?'CROWN':selected.toUpperCase()}</div><div className="style-heading"><h2>{style.name}</h2><p>{LABELS[selected]}</p></div><div className="slider-block"><div className="slider-actions"><Button aria-label="Previous style" onClick={()=>pick(design.styles[selected]-1)}><ChevronLeft/></Button><span className="selected-style-label">{String(design.styles[selected]+1).padStart(2,'0')} / 20</span><Button aria-label="Next style" onClick={()=>pick(design.styles[selected]+1)}><ChevronRight/></Button></div></div><div className="style-grid">{STYLES.map((s,i)=><button key={s.name} className={design.styles[selected]===i?'is-active':''} aria-pressed={design.styles[selected]===i} onClick={()=>pick(i)}><img src={`/styles/${String(i).padStart(2,"0")}.png`} alt="" loading="lazy" /><span className="tile-label">{s.name}</span></button>)}</div><Button className="apply-all" onClick={()=>apply(design.styles[selected])}>Apply to unlocked parts</Button>
 <AnatomyPanel design={design} onChange={commit}/><fieldset className="expression-controls"><legend>SURFACE</legend><label htmlFor="detail-size">Texture &amp; growth size</label><input id="detail-size" type="range" min="0.5" max="1.5" step="0.05" value={design.detail} onChange={e=>commit({...design,detail:+e.target.value})}/></fieldset><fieldset className="expression-controls"><legend>EXPRESSION</legend><label htmlFor="eye-mood">Eye expression</label><select id="eye-mood" value={design.eye} onChange={e=>commit({...design,eye:e.target.value as Design['eye']})}><option value="open">Curious</option><option value="sleepy">Unimpressed</option><option value="wide">Wide awake</option></select><label htmlFor="pupil-shape">Pupil shape</label><select id="pupil-shape" value={design.pupil} onChange={e=>commit({...design,pupil:e.target.value as PupilShape})}>{PUPILS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label htmlFor="pupil-size">Pupil size</label><input id="pupil-size" type="range" min="0.6" max="1.15" step="0.05" value={design.pupilSize} onChange={e=>commit({...design,pupilSize:+e.target.value})}/><label htmlFor="iris-size">Iris size</label><input id="iris-size" type="range" min="0.7" max="1.25" step="0.05" value={design.iris} onChange={e=>commit({...design,iris:+e.target.value})}/><label htmlFor="fur-length">Collar fluff</label><input id="fur-length" type="range" min="0.65" max="1.4" step="0.05" value={design.fur} onChange={e=>commit({...design,fur:+e.target.value})}/></fieldset><div className="display-switch"><Button variant={holo?'outline':'default'} aria-pressed={!holo} onClick={()=>setHolo(false)}>Solid</Button><Button variant={holo?'default':'outline'} aria-pressed={holo} onClick={()=>setHolo(true)}>Hologram</Button></div>
 </aside></section>{message&&<div className="myr-toast" role="status">{message}</div>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="creator-dialog"><DialogHeader><DialogTitle>Export specimen</DialogTitle><DialogDescription>Your current colors, expression, fur and ornaments travel with the model.</DialogDescription></DialogHeader><div className="export-options"><Button disabled={busy||!ready} onClick={()=>exportFile('glb')}>Download 3D model · GLB</Button><Button variant="outline" disabled={busy||!ready} onClick={()=>exportFile('obj')}>Download geometry · OBJ</Button><Button variant="outline" disabled={busy||!ready} onClick={()=>exportFile('png')}>Save this view · PNG</Button><Button variant="outline" onClick={save}>Save editable recipe · JSON</Button></div><p className="small-note">GLB keeps materials. OBJ exports geometry only. Models export assembled; the Parts view is for inspection. Hologram downloads keep the violet materials; screen effects stay in the customizer.</p></DialogContent></Dialog>
 </main>;
}





