import {mountWeaponStation} from './weapon-station.mjs';
const run=window.MBS_RUN;
let weaponStation=null;
let hologram=null,loadingHologram=false,expanded=false,busy=false,actionError='';
const steps=[['djscratch','DJ Scratch','/play/djscratch/'],['goon','Resistance · build a Reality Breaker','/play/goon/'],['lilboyfriend','Lil Boyfriend','/play/lilboyfriend/'],['corgi','Cortisol Corgi','/play/corgi/'],['hand','Helping Hand','/handborne/'],['armie','Survive Coach Armie','/games/armie/']];
const status=text=>document.querySelectorAll('[data-run-status]').forEach(el=>el.textContent=text);
async function board(){const body=document.getElementById('leaderRows');if(!body)return;const note=document.getElementById('leaderStatus');try{const {items}=await run.leaderboard();body.replaceChildren();for(const item of items){const row=document.createElement('tr');for(const text of [String(item.rank).padStart(2,'0'),'PRISONER '+item.djName,run.time(item.durationMs)]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}body.append(row);}note.textContent=items.length?'Live escapee records.':'No escapees on record yet. Your seat can be the first.';}catch(e){note.textContent=e.message;}}
async function paint(){const current=run.read(),done=new Set(current?.completed||[]),eligible=!!(current?.completedAt&&current?.installedAt);document.querySelectorAll('[data-run-name]').forEach(el=>el.textContent=current?.djName?'PRISONER '+current.djName:window.MBS_DJ.display());
 if(eligible&&!weaponStation&&document.getElementById('warWeaponStation'))weaponStation=mountWeaponStation(document.getElementById('warWeaponStation'),{choose:true,canUse:()=>{const r=run.read();return !!(r?.completedAt&&r?.installedAt);}});
 document.querySelectorAll('[data-run-time]').forEach(el=>el.textContent=current?run.time(current.durationMs??Date.now()-current.startedAt):'—');
 document.querySelectorAll('[data-run-checks]').forEach(list=>{list.replaceChildren();for(const [key,label,url] of [...steps,['app','Get the MYR5 app','https://myr5.mominc.online/install.html']]){const yes=key==='app'?!!current?.installedAt:done.has(key),row=document.createElement('li'),link=document.createElement('a'),mark=document.createElement('b');row.dataset.done=String(yes);link.href=url;link.textContent=label;mark.textContent=yes?'✓':'—';row.append(link,mark);list.append(row);}});
 const install=document.getElementById('getCoachApp');if(install){try{install.href='https://myr5.mominc.online/install.html#'+run.handoff();}catch{install.href='https://myr5.mominc.online/install.html';}}
 const join=document.getElementById('joinRankings');if(join){join.disabled=!eligible||busy||!!current?.joinedAt;join.textContent=current?.joinedAt?'YOUR RUN IS ON THE BOARD':'JOIN THE RANKINGS →';}
 if(document.getElementById('escapeCopy')&&!done.has('armie'))document.getElementById('escapeCopy').textContent='Your download is ready. Finish the required run and survive Coach Armie to earn a place on the Gala board.';
 const locked=document.getElementById('terminalLocked'),content=document.getElementById('warRoomContent');if(locked){locked.hidden=eligible;content.hidden=!eligible;if(eligible&&!loadingHologram){loadingHologram=true;board();const host=document.getElementById('terminalHologram');try{const {mountHologram}=await import('./hologram.mjs');hologram=await mountHologram(host);}catch{host.textContent='Hologram unavailable. The terminal is still connected.';}}}
 const monikerForm=document.getElementById('monikerForm');if(monikerForm){monikerForm.hidden=!done.has('djscratch')||!!current?.joinedAt;if(!monikerForm.contains(document.activeElement))monikerForm.elements.moniker.value=current?.moniker||'';}
 const joined=document.querySelector('[data-join-note]');if(joined)joined.textContent=current?.joinedAt?'Your DJ name and full-run time are public.':'Joining makes your DJ name and full-run time public.';
 status(actionError||run.error()||(current?.joinedAt?'Your run is saved on the Gala board.':eligible?'Clearance complete. Your run is ready for the board.':current?'Your run is saved here. Finish the remaining clearances.':'Connecting the run clock…'));
}
async function refresh(){actionError='';try{await run.flush();await run.refresh();await paint();}catch(e){status(e.message);}}
document.getElementById('refreshRun')?.addEventListener('click',refresh);document.getElementById('refreshLeaderboard')?.addEventListener('click',board);
document.getElementById('joinRankings')?.addEventListener('click',async()=>{actionError='';busy=true;paint();try{await run.join();if(document.getElementById('terminalLocked'))await board();else location.assign('/gala/terminal/');}catch(e){actionError=e.message;}finally{busy=false;await paint();}});
document.getElementById('monikerForm')?.addEventListener('submit',async e=>{e.preventDefault();actionError='';const button=e.currentTarget.querySelector('button'),tag=e.currentTarget.elements.moniker.value;button.disabled=true;try{await run.retag(tag);}catch(error){actionError=error.message;}finally{button.disabled=false;paint();}});
document.getElementById('splitHologram')?.addEventListener('click',e=>{expanded=!expanded;hologram?.split(expanded?1:0);e.currentTarget.textContent=expanded?'Reassemble the specimen':'Separate the specimen';});
window.addEventListener('mbs:run-update',paint);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
const clock=setInterval(()=>{const current=run.read();if(!document.hidden&&current&&!current.completedAt)document.querySelectorAll('[data-run-time]').forEach(el=>el.textContent=run.time(Date.now()-current.startedAt));},1000);
window.addEventListener('pagehide',()=>{clearInterval(clock);hologram?.dispose();weaponStation?.dispose();});paint();refresh();
