/* Mounts one channel fragment into a standalone play route, showing the GAME and none of the page.

   TWO PATHS, and which one a channel takes is DATA, never a guess. A channel converted by 2.18 has a
   module on disk, so mbs-channels.js carries `module: true` for it and channel-runtime.js owns the
   whole sequence: fetch, inject, beforeMount, mount, and one failure path. An unconverted one keeps
   the legacy contract this file has always used (scripts re-created copying textContent only),
   because those fragments were written against it and must not be edited to leave the television.

   THE ORDER IS THE WHOLE POINT. The isolation pass below has to run AFTER the fragment is in the
   document and BEFORE the game's own code initialises: these games measure layout as they start
   (fuel.js:479, lilboyfriend.js:795, armie.html:441), so a game that sees the advert around it
   measures the advert. On the legacy path that is simply the order of the statements; on the module
   path the runtime exposes opts.beforeMount for exactly this gap, and there is no other seam. */
(() => {
  const slug = document.documentElement.dataset.game;
  const host = document.getElementById("channel");
  const boot = document.getElementById("boot");
  const fail = (why) => {
    if (host) host.innerHTML = "";
    if (!boot) return;
    boot.innerHTML = '<p>This channel did not come in. <a href="../games/' + slug + '/">Go back</a> and try again.</p>';
    window.MBS && window.MBS.lifecycle && window.MBS.lifecycle.emit("GAME_ERROR", { stage: "mount", why: String(why).slice(0, 120) });
  };
  if (!slug || !/^[a-z0-9-]+$/.test(slug)) return fail("bad slug");

  /* Isolation is an ancestor-path reveal, never a blanket hide: display:none collapses descendant
     geometry and these games measure layout while they initialise (fuel.js:479, lilboyfriend.js:795,
     armie.html:441). So mark every root and every ancestor of a root as on-path, then hide only the
     OFF-path siblings. Interleaved game UI keeps its ancestor: fuel's live flavour readout sits inside
     the branding strip and djscratch's signal line sits inside the advert, and each survives while its
     ad-copy siblings go. Runs BEFORE the scripts are re-created, so a game never sees the page
     furniture, and never a frame of it.

     `hide` is the other half of the contract, and it is not optional. A root keeps its WHOLE subtree,
     so page furniture living INSIDE a game root can only be removed by naming it - djscratch's CUSTOM
     HANDS sign sits in the deck and links to a section that is now hidden. Roots union, hide subtracts;
     a list of roots alone cannot express the subtraction. */
  const NEVER_HIDE = /^(script|style|link|template|noscript|meta|title|base)$/;   /* elements that never render at all, so hiding them can only do harm */

  const one = (sel, kind) => {
    const hit = host.querySelectorAll(sel);
    if (hit.length !== 1) throw new Error(kind + " " + sel + " matched " + hit.length + ", want 1");
    return hit[0];
  };

  const isolate = (roots, hide) => {
    const keep = new Set(), path = new Set();
    for (const sel of roots) {
      const el = one(sel, "root");
      keep.add(el);
      for (let n = el.parentElement; n && n !== host; n = n.parentElement) path.add(n);
    }
    const walk = (parent) => {
      for (const el of parent.children) {
        if (keep.has(el)) continue;                                   /* a root: its whole subtree is the game */
        if (path.has(el)) walk(el);                                   /* on the way to a root: descend, hide its other children */
        else if (!NEVER_HIDE.test(el.tagName.toLowerCase())) el.classList.add("mbs-off");
      }
    };
    walk(host);
    for (const sel of hide) one(sel, "hide").classList.add("mbs-off");
  };

  /* Fail closed on the registry, not only on the DOM. An absent or empty roots list is the likeliest
     registry mistake, and treating it as "nothing to isolate" would quietly serve the whole page as
     the game, which is the exact defect Part A exists to remove. */
  const selectors = (v) => Array.isArray(v) && v.every(x => typeof x === "string" && x.trim());
  let roots, hide;
  try {
    const cfg = JSON.parse(document.documentElement.dataset.roots || "null");
    roots = Array.isArray(cfg) ? cfg : cfg && cfg.roots;
    hide = (cfg && !Array.isArray(cfg) && cfg.hide) || [];
    if (!selectors(roots) || !roots.length || !selectors(hide)) throw new Error("roots must be a non-empty list of selectors");
  } catch (e) { return fail(e.message || "bad roots"); }

  // suppressed channels: this loader accepts any valid slug, so it is a second way into a fragment
  // independently of tv.js. Read from window.MBS_CHANNELS (mbs-channels.js, generated by
  // tools/gen_channels.py from tv/channel-manifest.json's status field, loaded before this file on
  // every play route) rather than a hard-coded list, so a channel's status is the sole reachability
  // predicate everywhere, not just in tv.js.
  const chan = ((window.MBS_CHANNELS && window.MBS_CHANNELS.channels) || []).find(c => c.id === slug);
  if (chan && (chan.suppressed || chan.comingSoon)) return fail("channel unavailable");

  /* The two halves of a mount, named once and used by both paths: what happens between the fragment
     and the game, and what happens after the game is up. A missing selector, a duplicate match or a
     stale wrapper THROWS here and nothing mounts, rather than running the game with the whole page
     still around it. */
  const reveal = (root) => {
    if (root) document.title = (root.dataset.show || root.dataset.host || slug) + " | MBS";
    isolate(roots, hide);
  };
  const ready = () => {
    boot && boot.remove();
    window.MBS_ATMOSPHERE && window.MBS_ATMOSPHERE.mount(host, slug);
    window.dispatchEvent(new Event("resize"));   // a fragment inserted after load never gets one otherwise; games size themselves on resize
    window.MBS && window.MBS.bindFrames && window.MBS.bindFrames();       // an iframe game swallows its own pointer events
    window.MBS && window.MBS.lifecycle && window.MBS.lifecycle.ready();   // ready means mounted, never before
  };

  /* A CONVERTED channel (2.18). The runtime fetches and injects, calls reveal() through beforeMount,
     then mounts the module - so this file does not fetch at all on this path and there is one
     injection contract rather than two drifting copies. A throw out of reveal() fails the mount
     closed and is reported here, because serving the whole page as the game is the exact defect
     Part A exists to remove. */
  if (chan && chan.module && window.MBS_CH) {
    return window.MBS_CH.mount(slug, host, { beforeMount: reveal })
      .then(r => r.ok ? ready() : fail((r.reason && r.reason.message) || r.reason || "mount failed"))
      .catch(fail);
  }

  fetch("channels/" + slug + ".html", { cache: "no-store" })
    .then(r => r.ok ? r.text() : Promise.reject(r.status))
    .then(htmlText => {
      host.innerHTML = htmlText;

      try { reveal(host.querySelector("[data-host]")); }
      catch (e) { return fail(e.message); }

      host.querySelectorAll("script").forEach(old => {
        const s = document.createElement("script");
        s.textContent = old.textContent;
        old.replaceWith(s);
      });
      ready();
    })
    .catch(fail);
})();
