import { REGIONS, STYLES, type RegionId } from './catalog';
import { validateSelection, designCode, type HandDesign } from './recipe';
import { POSES, validatePose } from './poses';
import { DEFAULT_NAIL_SHAPE, NAIL_SHAPES, validateNailShape } from './nails';
import { SCALE_PATTERNS, validateScalePattern } from './scale-patterns';
type Tool = {name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
export function registerHandTools(read:()=>HandDesign, apply:(s:HandDesign)=>Promise<void>) {
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool) return () => {};
  const lifecycle=new AbortController();
  const tools:Tool[]=[
    {name:'read_hand_recipe',title:'Read hand recipe',description:'Read the six sections, nail shape, raised scales, current pose and restorable recipe.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...read(),code:designCode(read()),styles:STYLES.map(s=>({id:s.id,name:s.name})),poses:POSES.map(p=>({id:p.id,name:p.name})),nailShapes:[{id:DEFAULT_NAIL_SHAPE,name:'Creature default'},...NAIL_SHAPES.map(s=>({id:s.id,name:s.name}))],scalePatterns:SCALE_PATTERNS,regions:REGIONS})},
    {name:'configure_hand_sections',title:'Configure hand sections',description:`Apply all six section styles, preserving the nail shape and current pose. Style IDs are zero-based, 0 through ${STYLES.length-1}.`,inputSchema:{type:'object',properties:{sections:{type:'object',properties:Object.fromEntries(REGIONS.map(r=>[r.id,{type:'integer',minimum:0,maximum:STYLES.length-1}])),required:REGIONS.map(r=>r.id),additionalProperties:false}},required:['sections'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='sections'))throw new Error('Expected sections.');const sections=validateSelection((input as {sections:Record<RegionId,number>}).sections),next={...read(),sections};await apply(next);return {...next,code:designCode(next)};}},
    {name:'configure_hand_pose',title:'Change hand pose',description:'Pose the visible hand while preserving styles and nails. Automatic posing resumes after 15 seconds if playback is enabled.',inputSchema:{type:'object',properties:{pose:{type:'string',enum:POSES.map(p=>p.id)}},required:['pose'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='pose'))throw new Error('Expected a pose ID.');const pose=validatePose((input as {pose:unknown}).pose),next={...read(),pose};await apply(next);return {...next,code:designCode(next)};}},
    {name:'configure_nail_shape',title:'Change nail shape',description:'Change the five physical nails while preserving the creature materials and pose.',inputSchema:{type:'object',properties:{nailShape:{type:'string',enum:[DEFAULT_NAIL_SHAPE,...NAIL_SHAPES.map(s=>s.id)]}},required:['nailShape'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='nailShape'))throw new Error('Expected a nail shape.');const nailShape=validateNailShape((input as {nailShape:unknown}).nailShape),next={...read(),nailShape};await apply(next);return {...next,code:designCode(next)};}},
  ];
  tools.push({name:'configure_scale_pattern',title:'Change raised scales',description:'Add round, diamond, hexagonal or shield-shaped scale geometry across the hand, or turn it off. Keeps hand shape, materials, nails and pose.',inputSchema:{type:'object',properties:{scalePattern:{type:'string',enum:SCALE_PATTERNS.map(s=>s.id)}},required:['scalePattern'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='scalePattern'))throw new Error('Expected a scale pattern.');const scalePattern=validateScalePattern((input as {scalePattern:unknown}).scalePattern),next={...read(),scalePattern};await apply(next);return {...next,code:designCode(next)};}});
  for(const tool of tools) {try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  return ()=>lifecycle.abort();
}
