import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const values=new Map(),storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value))};
const sandbox={window:{dispatchEvent(){}},localStorage:storage,CustomEvent:class{}};
for(const file of ['weapons.js','progress.js'])vm.runInNewContext(readFileSync(new URL('../gala/'+file,import.meta.url),'utf8'),sandbox);
const W=sandbox.window.GalaWeapons,P=sandbox.window.GalaProgress;
const now=Date.now(),workouts=Array.from({length:28},(_,i)=>({id:`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`,user_id:'test-user',started_at:now-(7-Math.floor(i/4))*86400000,completed_at:now-(7-Math.floor(i/4))*86400000+60000,value:5,goal:5}));
P.importCoach({workouts,profiles:[],meals:[],reminders:[]});
assert.equal(P.read().activeDays,7);assert.equal(P.read().strength,8);
assert.equal(W.unlocked({type:'rapier',tier:4},P.read()),true);
assert.equal(W.unlocked({type:'rapier',tier:8},P.read()),false);
globalThis.window=sandbox.window;globalThis.localStorage=storage;globalThis.document={getElementById:()=>null};
const {activateGalaSpecial}=await import('../gala/weapon-station.mjs');
const before=JSON.stringify(P.read());
assert.equal((await activateGalaSpecial({type:'cannon',tier:20})).reason,'locked');
const fired=await activateGalaSpecial({type:'rapier',tier:4});assert.equal(fired.ok,true);
assert.equal((await activateGalaSpecial({type:'dagger',tier:4})).reason,'cooldown');
assert.equal(JSON.stringify(P.read()),before,'Gala effects never award workout XP');
assert.ok(JSON.parse(storage.getItem('mominc-gala-special-v1')).readyAt>Date.now());
const terminal=readFileSync(new URL('../gala/terminal/index.html',import.meta.url),'utf8');
assert.ok(terminal.indexOf('id="warWeaponStation"')>terminal.indexOf('id="warRoomContent" hidden'));
const entry=readFileSync(new URL('../tv/games/goon/index.html',import.meta.url),'utf8');
assert.ok(entry.includes('/gala/weapon-station.mjs?v=evolution1'));
console.log('Gala checks passed: imported Coach unlocks, locked upgrades, shared cooldown, persistence, unchanged XP, and game/terminal entry points.');
