const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom');
const {createCanvas}=require('@napi-rs/canvas');
const root=path.join(__dirname,'../gala');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://127.0.0.1:8820/gala/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,$=id=>w.document.getElementById(id),audios=[],downloads=[];
w.structuredClone=structuredClone;w.requestAnimationFrame=()=>0;w.matchMedia=()=>({matches:true});w.Blob=Blob;w.URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:test';};w.URL.revokeObjectURL=()=>{};
w.HTMLAnchorElement.prototype.click=function(){};
function surface(el){if(!el._canvas||el._canvas.width!==el.width||el._canvas.height!==el.height)el._canvas=createCanvas(el.width,el.height);return el._canvas;}
w.HTMLCanvasElement.prototype.getContext=function(){const c=surface(this).getContext('2d');return new Proxy(c,{get(target,key){if(key==='drawImage')return (image,...args)=>target.drawImage(image instanceof w.HTMLCanvasElement?surface(image):image,...args);const value=target[key];return typeof value==='function'?value.bind(target):value;},set(target,key,value){target[key]=value;return true;}});};
w.HTMLCanvasElement.prototype.toBlob=function(callback){callback(new Blob([surface(this).toBuffer('image/png')],{type:'image/png'}));};
w.Audio=class extends w.EventTarget{constructor(src){super();this.src=src;this.currentTime=0;this.duration=183.6;this.volume=1;this.error=null;this.plays=0;this.pauses=0;audios.push(this);}async play(){this.plays++;this.dispatchEvent(new w.Event('playing'));}pause(){this.pauses++;this.dispatchEvent(new w.Event('pause'));}load(){}};
for(const file of ['progress.js','weapons.js','armory.js','gramophone.js','avatar.js','gala.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
const W=w.GalaWeapons,P=w.GalaProgress,A=w.GalaAvatar,look=()=>JSON.parse(w.localStorage.getItem('mominc-avatar-v1'));
function countOpen(selector){return w.document.querySelectorAll(selector+'[aria-expanded="true"]').length;}
function consistent(){assert.ok(countOpen('#sections button')<=1);assert.ok(countOpen('#subsections button')<=1);const visible=['options','armory','silk-panel'].filter(id=>!$(id).hidden&&!$('wardrobe').hidden);assert.ok(visible.length<=1);assert.ok($('wardrobe').hidden||$('saved-looks').hidden);}
function select(id){for(const button of $('sections').children){if(button.getAttribute('aria-expanded')!=='true')button.click();consistent();const sub=w.document.querySelector(`[data-section="${id}"]`);if(sub){if(sub.getAttribute('aria-expanded')!=='true')sub.click();consistent();return sub;}}throw Error('Missing '+id);}
assert.equal($('sections').children.length,6);assert.equal($('subsections').children.length,5);consistent();
for(const section of A.sections){select(section.id);assert.equal($('options').hidden,false);assert.equal($('options').children.length,20);assert.equal($('avatar').style.getPropertyValue('--preview-scale'),'1.25');assert.equal($('avatar').dataset.focus,section.id);assert.ok(Number.isFinite(parseFloat($('avatar').style.getPropertyValue('--focus-x'))));const button=$('options').children[1];button.click();assert.equal(w.document.activeElement,$('options').children[1]);assert.equal($('avatar').style.getPropertyValue('--preview-scale'),'1.25');consistent();}
select('face');const faceOrigin=$('avatar').style.getPropertyValue('--focus-y');select('feet');assert.ok(parseFloat($('avatar').style.getPropertyValue('--focus-y'))>parseFloat(faceOrigin));
select('silk');assert.equal($('silk-panel').hidden,false);assert.equal($('options').hidden,true);$('dyes').children[3].click();assert.equal(look().dye,3);assert.equal($('dye-name').textContent,'Reactor satin');
select('weapons');assert.equal($('weapon-types').hidden,false);assert.equal($('weapon-tiers').hidden,true);assert.equal($('coach-progress-import').hidden,true);$('weapon-types').children[4].click();assert.equal(w.document.querySelector('[data-section="upgrades"]').getAttribute('aria-expanded'),'true');assert.equal($('weapon-types').hidden,true);assert.equal($('weapon-tiers').hidden,false);$('weapon-equip').click();assert.equal(look().weapon.type,'axe');assert.equal($('avatar').width,96);assert.ok(parseFloat($('avatar').style.getPropertyValue('--focus-x'))>80);
select('progress');assert.equal($('weapon-progress').hidden,false);assert.equal($('coach-progress-import').hidden,false);assert.equal($('weapon-types').hidden,true);assert.equal($('weapon-tiers').hidden,true);assert.equal($('avatar').style.getPropertyValue('--preview-scale'),'1');
select('share');assert.equal($('wardrobe').hidden,true);assert.equal($('saved-looks').hidden,false);assert.equal($('save-actions').hidden,false);assert.equal($('looks').hidden,true);$('save').click();select('saved');assert.equal($('looks').hidden,false);assert.equal($('save-actions').hidden,true);assert.equal($('looks').children.length,1);const stored=look();$('random').click();$('looks').children[0].click();assert.deepEqual(look(),stored);
const activeMenu=w.document.querySelector('#sections button[aria-expanded="true"]');activeMenu.click();consistent();assert.equal($('customizer-submenus').hidden,true);assert.equal($('wardrobe').hidden,true);assert.equal($('saved-looks').hidden,true);assert.equal($('avatar').style.getPropertyValue('--preview-scale'),'1');
activeMenu.click();assert.equal($('saved-looks').hidden,false);const activeSub=w.document.querySelector('#subsections button[aria-expanded="true"]');activeSub.click();consistent();assert.equal(countOpen('#subsections button'),0);assert.equal($('saved-looks').hidden,true);activeSub.click();assert.equal($('saved-looks').hidden,false);
// Zoom is a display-only transform: portrait downloads retain the complete image.
select('feet');$('png').click();assert.equal(downloads.at(-1).type,'image/png');assert.equal($('avatar').height,96);assert.equal($('avatar').width,96);
console.log('PASS: six exclusive menus; all 17 part submenus; exclusive silk, weapons, upgrades, progress, saved and sharing views; weapon family advances to upgrades; remembered sections; collapse/reopen; 25% anchored zoom; complete portrait exports.');dom.window.close();
