# -*- coding: utf-8 -*-
"""Generates two files from tv/channel-manifest.json, the single source of truth (D.1.1):

  1. tv/mbs-channels.js - a CLASSIC script (no import/export) setting window.MBS_CHANNELS, included
     before tv.js and before mbs-shim.js everywhere either is loaded. Replaces tv.js's CHANNELS/
     COMING_SOON/ACTIVE_UNLOCK and mbs-shim.js's duplicate ACTIVE_UNLOCK/FORM_SITES (2.2, 2.3, 2.3b).
  2. tv/registry.json - the forward projection described in PLAN-r8.md D.1.1: drop manifest-owned
     fields already projected under new names, keep the twenty-field registry passthrough verbatim,
     emit `status` only when it is not "live", and include only inRegistry channels (2.4).

Registry emission order is ascending `channel` number among inRegistry channels, matching the
committed file - NOT the manifest's own array order, which is presentation order for the sidebar
(mominc first, then fuel/goon before the rest). D.1.1's "order is the manifest's order" holds for the
*relative* order of inRegistry records, which happens to be ascending-by-channel in both files; sorting
here is what makes that hold regardless of how the manifest array itself is arranged.

Run:  python tools/gen_channels.py
"""
import io, json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
MANIFEST_PATH = os.path.join(ROOT, "tv", "channel-manifest.json")
CHANNELS_JS_PATH = os.path.join(ROOT, "tv", "mbs-channels.js")
REGISTRY_PATH = os.path.join(ROOT, "tv", "registry.json")

# Sidebar layout flags: presentation-only (which slot the card sits in), not channel identity, so they
# live here rather than in the D.1.1 schema.
HEAD_IDS = {"mominc"}
HALF_IDS = {"fuel", "goon"}

PASSTHROUGH_FIELDS = [
    "host", "eyebrow", "genre", "premise", "cta", "does", "duration", "input", "hero", "teaser",
    "roots", "hide", "palette", "finish", "cta2", "progress_key", "continue_cta", "profile_intro",
    "profile_questions", "share_image",
]


def load_manifest():
    return json.load(io.open(MANIFEST_PATH, encoding="utf-8"))


def gen_channels_js(manifest):
    channels = manifest["channels"]
    out = []
    for c in channels:
        out.append({
            "id": c["id"],
            "ch": c["channel"],
            "name": c["lcdName"],
            "head": c["id"] in HEAD_IDS,
            "half": c["id"] in HALF_IDS,
            "comingSoon": c["status"] == "coming_soon",
            "suppressed": c.get("suppressed") is not None,
        })
    active = [c["id"] for c in channels if c["active"]]
    # No manifest field distinguishes "asks the visitor for a form" from "active unlock node" today -
    # the two sets are identical in the current tree (lilboyfriend, djscratch, corgi, fuel). Derived
    # from `active` rather than inventing a field with no independent data behind it yet; a future
    # channel that is active but form-less (or vice versa) needs its own manifest field at that point.
    forms = list(active)

    payload = json.dumps({"channels": out, "active": active, "forms": forms}, ensure_ascii=False, indent=2)
    js = (
        "// GENERATED by tools/gen_channels.py from tv/channel-manifest.json. Do not hand-edit.\n"
        "// Classic script (no import/export): loaded before tv.js and before mbs-shim.js everywhere\n"
        "// either is loaded, so both can read window.MBS_CHANNELS with no module graph involved.\n"
        "window.MBS_CHANNELS = " + payload + ";\n"
    )
    with io.open(CHANNELS_JS_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(js)
    return CHANNELS_JS_PATH


def gen_registry(manifest):
    games = [c for c in manifest["channels"] if c["inRegistry"]]
    games.sort(key=lambda c: c["channel"])
    out_games = []
    for c in games:
        g = {"slug": c["id"], "ch": c["channel"]}
        if c["status"] != "live":                 # committed order: status sits right after ch
            g["status"] = c["status"]
        g["mission_id"] = c.get("missionId") or ""
        g["title"] = c["title"]
        reg = c["registry"] or {}
        for f in PASSTHROUGH_FIELDS:
            g[f] = reg.get(f)
        out_games.append(g)

    registry = {
        "note": manifest["note"],
        "games": out_games,
        "live": manifest["live"],
        "identity_api": manifest["identity_api"],
        "api_base": manifest["api_base"],
    }
    with io.open(REGISTRY_PATH, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(registry, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    return REGISTRY_PATH


def main():
    manifest = load_manifest()
    p1 = gen_channels_js(manifest)
    p2 = gen_registry(manifest)
    print(p1)
    print(p2)


if __name__ == "__main__":
    main()
